Add Clojure

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -142,3 +142,120 @@ echo "-----> Bundling PHP version $PHP_VERSION"
 curl --silent --max-time 60 --location "$PHP_URL" | tar xz
 
 ln -s /app/php/bin/php bin/php
+
+export BUILD_DIR=$1
+export CACHE_DIR=$2
+
+# Load common JVM functionality from https://github.com/heroku/heroku-buildpack-jvm-common
+JVM_COMMON_BUILDPACK=https://heroku-jvm-common.s3.amazonaws.com/jvm-buildpack-common.tar.gz
+curl --silent --location $JVM_COMMON_BUILDPACK | tar -x bin/java -zO > /tmp/jvm-common
+source /tmp/jvm-common
+
+# JDK version
+if [ -z "$JAVA_VERSION" ]; then # could be set using user_env_compile
+    if [ -f "${BUILD_DIR}/system.properties" ]; then
+        JAVA_VERSION=$(get_app_system_value ${BUILD_DIR}/system.properties "java.runtime.version")
+    else
+        JAVA_VERSION=$DEFAULT_JDK_VERSION
+    fi
+fi
+
+# Install JDK
+if [ "$(is_supported_java_version ${JAVA_VERSION})" = "true" ]; then
+    echo -n "-----> Installing OpenJDK ${JAVA_VERSION}..."
+    install_java ${BUILD_DIR} ${JAVA_VERSION}
+    jdk_overlay ${BUILD_DIR}
+    echo "done"
+else
+    echo " !     Unsupported Java version: $JAVA_VERSION"
+    exit 1
+fi
+
+# Make sure new JDK is visible to Leiningen
+export PATH="$HOME/.jdk/bin:$PATH"
+
+LEIN_VERSION="1.7.1"
+LEIN_BIN_SOURCE="$(dirname $0)/../opt/lein1"
+if [ "$LEIN_DEV" = "" ]; then
+    export LEIN_NO_DEV=y
+fi
+RLWRAP=yes
+
+# install leiningen jar
+LEIN_JAR_URL="https://heroku-buildpack-clojure.s3.amazonaws.com/leiningen-$LEIN_VERSION-standalone.jar"
+LEIN_JAR_CACHE_PATH="$CACHE_DIR/leiningen-$LEIN_VERSION-standalone.jar"
+LEIN_JAR_SLUG_PATH="$BUILD_DIR/.lein/leiningen-$LEIN_VERSION-standalone.jar"
+
+if [ ! -r "$LEIN_JAR_CACHE_PATH" ]; then
+    echo "-----> Installing Leiningen"
+    echo "       Downloading: leiningen-$LEIN_VERSION-standalone.jar"
+    mkdir -p $(dirname $LEIN_JAR_CACHE_PATH)
+    curl --silent --show-error --max-time 120 -L -o "$LEIN_JAR_CACHE_PATH" $LEIN_JAR_URL
+else
+    echo "-----> Using cached Leiningen $LEIN_VERSION"
+fi
+
+mkdir -p "$BUILD_DIR/.lein"
+cp "$LEIN_JAR_CACHE_PATH" "$LEIN_JAR_SLUG_PATH"
+
+# install rlwrap binary on lein 1.x
+if [ "$RLWRAP" = "yes" ]; then
+    RLWRAP_BIN_URL="https://s3.amazonaws.com/heroku-buildpack-clojure/rlwrap-0.3.7"
+    RLWRAP_BIN_PATH=$BUILD_DIR"/.lein/bin/rlwrap"
+    echo "       Downloading: rlwrap-0.3.7"
+    mkdir -p $(dirname $RLWRAP_BIN_PATH)
+    curl --silent --show-error --max-time 60 -L -o $RLWRAP_BIN_PATH $RLWRAP_BIN_URL
+    chmod +x $RLWRAP_BIN_PATH
+fi
+
+# install lein script
+LEIN_BIN_PATH=$BUILD_DIR"/.lein/bin/lein"
+echo "       Writing: lein script"
+mkdir -p $(dirname $LEIN_BIN_PATH)
+cp $LEIN_BIN_SOURCE $LEIN_BIN_PATH
+sed -i s/##LEIN_VERSION##/$LEIN_VERSION/ $LEIN_BIN_PATH
+
+# create user-level profiles
+LEIN_PROFILES_SOURCE="$(dirname $0)/../opt/profiles.clj"
+cp -n $LEIN_PROFILES_SOURCE "$BUILD_DIR/.lein/profiles.clj"
+
+# unpack existing cache
+CACHE_STORE_DIR=$CACHE_DIR"/.m2"
+CACHE_TARGET_DIR=$BUILD_DIR"/.m2"
+rm -rf $CACHE_TARGET_DIR
+if [ -d $CACHE_STORE_DIR ]; then
+    cp -r $CACHE_STORE_DIR $CACHE_TARGET_DIR
+else
+    mkdir -p $CACHE_TARGET_DIR
+fi
+
+cd $BUILD_DIR
+PATH=.lein/bin:$PATH JVM_OPTS="-Xmx600m" \
+    LEIN_JVM_OPTS="-Xmx400m -Duser.home=$BUILD_DIR" \
+    $BUILD_COMMAND 2>&1 | sed -u 's/^/       /'
+if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to build."
+    exit 1
+fi
+
+# populate profile.d
+PROFILE_PATH="$BUILD_DIR/.profile.d/clojure.sh"
+mkdir -p $(dirname $PROFILE_PATH)
+
+echo "export JVM_OPTS=\"\${JVM_OPTS:--Xmx400m -Dfile.encoding=UTF-8}\"" >> $PROFILE_PATH
+echo "export LEIN_NO_DEV=\"\${LEIN_NO_DEV:-yes}\"" >> $PROFILE_PATH
+echo "export PATH=\"\$HOME/.jdk/bin:$PATH:\$HOME/.lein/bin\"" >> $PROFILE_PATH
+
+# repack cache with new assets
+rm -rf $CACHE_STORE_DIR
+mkdir -p $(dirname $CACHE_STORE_DIR)
+cp -r $CACHE_TARGET_DIR $CACHE_STORE_DIR
+
+if [ "$LEIN_INCLUDE_IN_SLUG" = "no" ]; then
+    rm "$LEIN_JAR_SLUG_PATH"
+    rm -rf "$CACHE_TARGET_DIR"
+fi
+
+if [ "$LEIN_VERSION" = "1.7.1" ]; then
+    rm -rf "$CACHE_TARGET_DIR"
+fi
